# Generated by Django 4.1.7 on 2023-04-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='award_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification_improvement_duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification_improvement_end_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification_improvement_start_date',
            field=models.CharField(max_length=255),
        ),
    ]
