# Generated by Django 4.1.7 on 2023-04-20 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('identity_document', models.CharField(max_length=255)),
                ('registered_address', models.CharField(max_length=255)),
                ('residence_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('publication_type', models.CharField(max_length=50)),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_edition_name', models.CharField(max_length=255)),
                ('publication_edition_year', models.PositiveIntegerField()),
                ('publication_edition_number', models.PositiveIntegerField()),
                ('coauthors', models.CharField(max_length=255)),
                ('supporting_documents', models.CharField(max_length=255)),
                ('award_type', models.CharField(max_length=50)),
                ('honorary_title', models.CharField(max_length=50)),
                ('award_date', models.DateField()),
                ('qualification_improvement_form', models.CharField(max_length=50)),
                ('qualification_improvement_city', models.CharField(max_length=255)),
                ('qualification_improvement_organization_name', models.CharField(max_length=255)),
                ('qualification_improvement_start_date', models.DateField()),
                ('qualification_improvement_end_date', models.DateField()),
                ('qualification_improvement_duration', models.PositiveIntegerField()),
                ('qualification_improvement_topic', models.CharField(max_length=255)),
                ('qualification_improvement_supporting_document', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
