# Generated by Django 4.1.7 on 2023-04-20 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('identity_document', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=50)),
                ('study_type', models.CharField(max_length=50)),
                ('registered_address', models.CharField(max_length=255)),
                ('residence_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('course_number', models.PositiveIntegerField()),
                ('parents', models.CharField(max_length=255)),
                ('parents_contacts', models.CharField(max_length=255)),
                ('parents_work_place', models.CharField(max_length=255)),
                ('certificates_or_olympiads', models.CharField(max_length=255)),
                ('disability', models.BooleanField(default=False)),
                ('hobbies', models.CharField(max_length=255)),
                ('religious_beliefs', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
