# Generated by Django 4.1.7 on 2023-04-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_users',
        ),
    ]
